// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Session struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Email       string
	DisplayName string
	TokenHash   []byte
	ExpiresAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
