// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :execrows
UPDATE sessions
SET expires_at = $1, updated_at = now()
WHERE id = $2
`

type ExtendSessionParams struct {
	ExpiresAt time.Time
	ID        uuid.UUID
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendSession, arg.ExpiresAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, owner_id, email, display_name, expires_at
FROM sessions
WHERE token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Email       string
	DisplayName string
	ExpiresAt   time.Time
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Email,
		&i.DisplayName,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (id, owner_id, email, display_name, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSessionParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Email       string
	DisplayName string
	TokenHash   []byte
	ExpiresAt   time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.OwnerID,
		arg.Email,
		arg.DisplayName,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}
