version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns: ["*"]

  # TODO: add /web in P5.1.
  - package-ecosystem: gomod
    directories:
      - /pkg
      - /gen/go
      - /services/*
      - /tools
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      go-minor-patch:
        update-types: [minor, patch]
