// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChannelSetting struct {
	OwnerID   uuid.UUID
	Channel   string
	Enabled   bool
	QuietFrom pgtype.Time
	QuietTo   pgtype.Time
	Version   int64
	UpdatedAt time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Notification struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Type          string
	Title         string
	Body          *string
	Link          *string
	SourceEventID *uuid.UUID
	ReadAt        *time.Time
	CreatedAt     time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}
