// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*)::int FROM notifications
WHERE owner_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, ownerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnread, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notifications (id, owner_id, type, title, body, link, source_event_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source_event_id) DO NOTHING
RETURNING id, owner_id, type, title, body, link, source_event_id, read_at, created_at
`

type InsertNotificationParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Type          string
	Title         string
	Body          *string
	Link          *string
	SourceEventID *uuid.UUID
	CreatedAt     time.Time
}

// Returns no row when a notification for source_event_id already exists, so a
// redelivered event adds nothing.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ID,
		arg.OwnerID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.SourceEventID,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.SourceEventID,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, owner_id, type, title, body, link, source_event_id, read_at, created_at FROM notifications
WHERE owner_id = $1
  AND (NOT $2::boolean OR read_at IS NULL)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListNotificationsParams struct {
	OwnerID        uuid.UUID
	UnreadOnly     bool
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (created_at, id), newest first. A NULL after_* pair
// means the first page.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.OwnerID,
		arg.UnreadOnly,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.SourceEventID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsAfter = `-- name: ListNotificationsAfter :many
SELECT id, owner_id, type, title, body, link, source_event_id, read_at, created_at FROM notifications
WHERE owner_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListNotificationsAfterParams struct {
	OwnerID  uuid.UUID
	AfterID  uuid.UUID
	RowLimit int32
}

// Replays what a stream missed. Ids are UUIDv7, so id order is creation order.
func (q *Queries) ListNotificationsAfter(ctx context.Context, arg ListNotificationsAfterParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsAfter, arg.OwnerID, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.SourceEventID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications SET read_at = $1
WHERE owner_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	ReadAt  *time.Time
	OwnerID uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.ReadAt, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :execrows
UPDATE notifications SET read_at = $1
WHERE owner_id = $2 AND id = ANY($3::uuid[]) AND read_at IS NULL
`

type MarkNotificationsReadParams struct {
	ReadAt  *time.Time
	OwnerID uuid.UUID
	Ids     []uuid.UUID
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationsRead, arg.ReadAt, arg.OwnerID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
