// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelSetting = `-- name: GetChannelSetting :one
SELECT owner_id, channel, enabled, quiet_from, quiet_to, version, updated_at FROM channel_settings
WHERE owner_id = $1 AND channel = $2
`

type GetChannelSettingParams struct {
	OwnerID uuid.UUID
	Channel string
}

func (q *Queries) GetChannelSetting(ctx context.Context, arg GetChannelSettingParams) (ChannelSetting, error) {
	row := q.db.QueryRow(ctx, getChannelSetting, arg.OwnerID, arg.Channel)
	var i ChannelSetting
	err := row.Scan(
		&i.OwnerID,
		&i.Channel,
		&i.Enabled,
		&i.QuietFrom,
		&i.QuietTo,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChannelSetting = `-- name: InsertChannelSetting :one
INSERT INTO channel_settings (owner_id, channel, enabled, quiet_from, quiet_to)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, channel) DO NOTHING
RETURNING owner_id, channel, enabled, quiet_from, quiet_to, version, updated_at
`

type InsertChannelSettingParams struct {
	OwnerID   uuid.UUID
	Channel   string
	Enabled   bool
	QuietFrom pgtype.Time
	QuietTo   pgtype.Time
}

// Returns no row when the owner already has a setting for the channel.
func (q *Queries) InsertChannelSetting(ctx context.Context, arg InsertChannelSettingParams) (ChannelSetting, error) {
	row := q.db.QueryRow(ctx, insertChannelSetting,
		arg.OwnerID,
		arg.Channel,
		arg.Enabled,
		arg.QuietFrom,
		arg.QuietTo,
	)
	var i ChannelSetting
	err := row.Scan(
		&i.OwnerID,
		&i.Channel,
		&i.Enabled,
		&i.QuietFrom,
		&i.QuietTo,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwners = `-- name: ListOwners :many
SELECT owner_id FROM notifications
UNION
SELECT owner_id FROM channel_settings
`

// Every owner taiko has heard of: one with a notification or a setting.
func (q *Queries) ListOwners(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var owner_id uuid.UUID
		if err := rows.Scan(&owner_id); err != nil {
			return nil, err
		}
		items = append(items, owner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelSetting = `-- name: UpdateChannelSetting :one
UPDATE channel_settings SET
    enabled = $1,
    quiet_from = $2,
    quiet_to = $3,
    version = version + 1,
    updated_at = now()
WHERE owner_id = $4 AND channel = $5 AND version = $6
RETURNING owner_id, channel, enabled, quiet_from, quiet_to, version, updated_at
`

type UpdateChannelSettingParams struct {
	Enabled   bool
	QuietFrom pgtype.Time
	QuietTo   pgtype.Time
	OwnerID   uuid.UUID
	Channel   string
	Version   int64
}

// Returns no row when the stored version is not @version.
func (q *Queries) UpdateChannelSetting(ctx context.Context, arg UpdateChannelSettingParams) (ChannelSetting, error) {
	row := q.db.QueryRow(ctx, updateChannelSetting,
		arg.Enabled,
		arg.QuietFrom,
		arg.QuietTo,
		arg.OwnerID,
		arg.Channel,
		arg.Version,
	)
	var i ChannelSetting
	err := row.Scan(
		&i.OwnerID,
		&i.Channel,
		&i.Enabled,
		&i.QuietFrom,
		&i.QuietTo,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
