// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activities.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getActivity = `-- name: GetActivity :one
SELECT id, owner_id, item_id, summary, minutes, occurred_on, tags, created_at FROM activities WHERE owner_id = $1 AND id = $2
`

type GetActivityParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivity, arg.OwnerID, arg.ID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ItemID,
		&i.Summary,
		&i.Minutes,
		&i.OccurredOn,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO activities (id, owner_id, item_id, summary, minutes, occurred_on, tags, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, item_id, summary, minutes, occurred_on, tags, created_at
`

type InsertActivityParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	ItemID     *uuid.UUID
	Summary    string
	Minutes    *int32
	OccurredOn time.Time
	Tags       []string
	CreatedAt  time.Time
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, insertActivity,
		arg.ID,
		arg.OwnerID,
		arg.ItemID,
		arg.Summary,
		arg.Minutes,
		arg.OccurredOn,
		arg.Tags,
		arg.CreatedAt,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ItemID,
		&i.Summary,
		&i.Minutes,
		&i.OccurredOn,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, owner_id, item_id, summary, minutes, occurred_on, tags, created_at FROM activities
WHERE owner_id = $1
  AND ($2::uuid IS NULL OR item_id = $2::uuid)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListActivitiesParams struct {
	OwnerID        uuid.UUID
	ItemID         *uuid.UUID
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (created_at, id), newest first. A NULL item_id means
// every activity.
func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.OwnerID,
		arg.ItemID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ItemID,
			&i.Summary,
			&i.Minutes,
			&i.OccurredOn,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
