// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getItem = `-- name: GetItem :one
SELECT id, owner_id, title, kind, url, status, started_on, completed_on, insight, version, created_at, updated_at, archived_at FROM items WHERE owner_id = $1 AND id = $2 AND archived_at IS NULL
`

type GetItemParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.OwnerID, arg.ID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Kind,
		&i.Url,
		&i.Status,
		&i.StartedOn,
		&i.CompletedOn,
		&i.Insight,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (id, owner_id, title, kind, url, insight, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, owner_id, title, kind, url, status, started_on, completed_on, insight, version, created_at, updated_at, archived_at
`

type InsertItemParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Title   string
	Kind    string
	Url     *string
	Insight *string
	Now     time.Time
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Kind,
		arg.Url,
		arg.Insight,
		arg.Now,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Kind,
		&i.Url,
		&i.Status,
		&i.StartedOn,
		&i.CompletedOn,
		&i.Insight,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, owner_id, title, kind, url, status, started_on, completed_on, insight, version, created_at, updated_at, archived_at FROM items
WHERE owner_id = $1 AND archived_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND (
    $3::timestamptz IS NULL
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListItemsParams struct {
	OwnerID        uuid.UUID
	Status         *string
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (created_at, id), newest first. A NULL after_* pair
// means the first page; a NULL status means every status.
func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.OwnerID,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Kind,
			&i.Url,
			&i.Status,
			&i.StartedOn,
			&i.CompletedOn,
			&i.Insight,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items SET
    title = $1,
    kind = $2,
    url = $3,
    insight = $4,
    version = version + 1,
    updated_at = $5
WHERE id = $6 AND owner_id = $7 AND version = $8 AND archived_at IS NULL
RETURNING id, owner_id, title, kind, url, status, started_on, completed_on, insight, version, created_at, updated_at, archived_at
`

type UpdateItemParams struct {
	Title   string
	Kind    string
	Url     *string
	Insight *string
	Now     time.Time
	ID      uuid.UUID
	OwnerID uuid.UUID
	Version int32
}

// Writes every editable column; the caller applies the field mask to the
// current row first. Returns no row when the version is stale.
func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Title,
		arg.Kind,
		arg.Url,
		arg.Insight,
		arg.Now,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Kind,
		&i.Url,
		&i.Status,
		&i.StartedOn,
		&i.CompletedOn,
		&i.Insight,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE items SET
    status = $1,
    started_on = $2,
    completed_on = $3,
    version = version + 1,
    updated_at = $4
WHERE id = $5 AND owner_id = $6 AND version = $7 AND archived_at IS NULL
RETURNING id, owner_id, title, kind, url, status, started_on, completed_on, insight, version, created_at, updated_at, archived_at
`

type UpdateItemStatusParams struct {
	Status      string
	StartedOn   *time.Time
	CompletedOn *time.Time
	Now         time.Time
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Version     int32
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemStatus,
		arg.Status,
		arg.StartedOn,
		arg.CompletedOn,
		arg.Now,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Kind,
		&i.Url,
		&i.Status,
		&i.StartedOn,
		&i.CompletedOn,
		&i.Insight,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
