// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	ItemID     *uuid.UUID
	Summary    string
	Minutes    *int32
	OccurredOn time.Time
	Tags       []string
	CreatedAt  time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Item struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	Kind        string
	Url         *string
	Status      string
	StartedOn   *time.Time
	CompletedOn *time.Time
	Insight     *string
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}
