// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type GithubSnapshot struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	TakenAt       time.Time
	Repos         []byte
	Contributions []byte
	Etag          *string
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Suggestion struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Target    string
	Section   string
	Before    *string
	After     string
	Reason    string
	Evidence  []byte
	State     string
	CreatedAt time.Time
	DecidedAt *time.Time
}
