// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSnapshot = `-- name: InsertSnapshot :one
INSERT INTO github_snapshots (id, owner_id, taken_at, repos, contributions, etag)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, taken_at, repos, contributions, etag
`

type InsertSnapshotParams struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	TakenAt       time.Time
	Repos         []byte
	Contributions []byte
	Etag          *string
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (GithubSnapshot, error) {
	row := q.db.QueryRow(ctx, insertSnapshot,
		arg.ID,
		arg.OwnerID,
		arg.TakenAt,
		arg.Repos,
		arg.Contributions,
		arg.Etag,
	)
	var i GithubSnapshot
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.TakenAt,
		&i.Repos,
		&i.Contributions,
		&i.Etag,
	)
	return i, err
}

const listLatestSnapshots = `-- name: ListLatestSnapshots :many
SELECT id, owner_id, taken_at, repos, contributions, etag FROM github_snapshots
WHERE owner_id = $1
ORDER BY taken_at DESC, id DESC
LIMIT $2
`

type ListLatestSnapshotsParams struct {
	OwnerID  uuid.UUID
	RowLimit int32
}

// The newest snapshots of the owner, newest first, for the ETag and the diff.
func (q *Queries) ListLatestSnapshots(ctx context.Context, arg ListLatestSnapshotsParams) ([]GithubSnapshot, error) {
	rows, err := q.db.Query(ctx, listLatestSnapshots, arg.OwnerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubSnapshot{}
	for rows.Next() {
		var i GithubSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.TakenAt,
			&i.Repos,
			&i.Contributions,
			&i.Etag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotOwners = `-- name: ListSnapshotOwners :many
SELECT DISTINCT owner_id FROM github_snapshots ORDER BY owner_id
`

// Owners who have synced at least once; the daily sync covers them.
func (q *Queries) ListSnapshotOwners(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSnapshotOwners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var owner_id uuid.UUID
		if err := rows.Scan(&owner_id); err != nil {
			return nil, err
		}
		items = append(items, owner_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
