// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suggestions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const decideSuggestion = `-- name: DecideSuggestion :one
UPDATE suggestions SET state = $1, decided_at = $2
WHERE owner_id = $3 AND id = $4 AND state = 'open'
RETURNING id, owner_id, target, section, before, after, reason, evidence, state, created_at, decided_at
`

type DecideSuggestionParams struct {
	State     string
	DecidedAt *time.Time
	OwnerID   uuid.UUID
	ID        uuid.UUID
}

// Returns no row unless the suggestion is open, so a decision is made once.
func (q *Queries) DecideSuggestion(ctx context.Context, arg DecideSuggestionParams) (Suggestion, error) {
	row := q.db.QueryRow(ctx, decideSuggestion,
		arg.State,
		arg.DecidedAt,
		arg.OwnerID,
		arg.ID,
	)
	var i Suggestion
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Target,
		&i.Section,
		&i.Before,
		&i.After,
		&i.Reason,
		&i.Evidence,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getSuggestion = `-- name: GetSuggestion :one
SELECT id, owner_id, target, section, before, after, reason, evidence, state, created_at, decided_at FROM suggestions WHERE owner_id = $1 AND id = $2
`

type GetSuggestionParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetSuggestion(ctx context.Context, arg GetSuggestionParams) (Suggestion, error) {
	row := q.db.QueryRow(ctx, getSuggestion, arg.OwnerID, arg.ID)
	var i Suggestion
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Target,
		&i.Section,
		&i.Before,
		&i.After,
		&i.Reason,
		&i.Evidence,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertSuggestion = `-- name: InsertSuggestion :one
INSERT INTO suggestions (id, owner_id, target, section, before, after, reason, evidence, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, target, section, before, after, reason, evidence, state, created_at, decided_at
`

type InsertSuggestionParams struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Target    string
	Section   string
	Before    *string
	After     string
	Reason    string
	Evidence  []byte
	CreatedAt time.Time
}

func (q *Queries) InsertSuggestion(ctx context.Context, arg InsertSuggestionParams) (Suggestion, error) {
	row := q.db.QueryRow(ctx, insertSuggestion,
		arg.ID,
		arg.OwnerID,
		arg.Target,
		arg.Section,
		arg.Before,
		arg.After,
		arg.Reason,
		arg.Evidence,
		arg.CreatedAt,
	)
	var i Suggestion
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Target,
		&i.Section,
		&i.Before,
		&i.After,
		&i.Reason,
		&i.Evidence,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listSuggestions = `-- name: ListSuggestions :many
SELECT id, owner_id, target, section, before, after, reason, evidence, state, created_at, decided_at FROM suggestions
WHERE owner_id = $1
  AND ($2::text IS NULL OR state = $2::text)
  AND ($3::text IS NULL OR target = $3::text)
  AND (
    $4::timestamptz IS NULL
    OR (created_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListSuggestionsParams struct {
	OwnerID        uuid.UUID
	State          *string
	Target         *string
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (created_at, id), newest first. A NULL after_* pair
// means the first page; a NULL state or target means any.
func (q *Queries) ListSuggestions(ctx context.Context, arg ListSuggestionsParams) ([]Suggestion, error) {
	rows, err := q.db.Query(ctx, listSuggestions,
		arg.OwnerID,
		arg.State,
		arg.Target,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suggestion{}
	for rows.Next() {
		var i Suggestion
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Target,
			&i.Section,
			&i.Before,
			&i.After,
			&i.Reason,
			&i.Evidence,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
