// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Posting struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	SourceID   uuid.UUID
	ExternalID string
	Title      string
	Company    *string
	Url        *string
	Location   *string
	PostedAt   *time.Time
	Raw        []byte
	SavedJobID *uuid.UUID
	CreatedAt  time.Time
}

type Preference struct {
	OwnerID    uuid.UUID
	Roles      []string
	Locations  []string
	MustHave   []string
	NiceToHave []string
	Exclude    []string
	MinScore   float32
	UpdatedAt  time.Time
}

type Score struct {
	PostingID uuid.UUID
	Score     float32
	Reasons   []byte
	ScoredBy  string
	CreatedAt time.Time
}

type Source struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Kind      string
	Config    []byte
	Schedule  string
	Enabled   bool
	LastRunAt *time.Time
	LastError *string
}
