// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: postings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPosting = `-- name: GetPosting :one
SELECT id, owner_id, source_id, external_id, title, company, url, location, posted_at, raw, saved_job_id, created_at FROM postings WHERE owner_id = $1 AND id = $2
`

type GetPostingParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetPosting(ctx context.Context, arg GetPostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, getPosting, arg.OwnerID, arg.ID)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Location,
		&i.PostedAt,
		&i.Raw,
		&i.SavedJobID,
		&i.CreatedAt,
	)
	return i, err
}

const getPostingByID = `-- name: GetPostingByID :one
SELECT id, owner_id, source_id, external_id, title, company, url, location, posted_at, raw, saved_job_id, created_at FROM postings WHERE id = $1
`

// For a job that works for an owner it already knows.
func (q *Queries) GetPostingByID(ctx context.Context, id uuid.UUID) (Posting, error) {
	row := q.db.QueryRow(ctx, getPostingByID, id)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Location,
		&i.PostedAt,
		&i.Raw,
		&i.SavedJobID,
		&i.CreatedAt,
	)
	return i, err
}

const getScore = `-- name: GetScore :one
SELECT posting_id, score, reasons, scored_by, created_at FROM scores WHERE posting_id = $1
`

func (q *Queries) GetScore(ctx context.Context, postingID uuid.UUID) (Score, error) {
	row := q.db.QueryRow(ctx, getScore, postingID)
	var i Score
	err := row.Scan(
		&i.PostingID,
		&i.Score,
		&i.Reasons,
		&i.ScoredBy,
		&i.CreatedAt,
	)
	return i, err
}

const listPostings = `-- name: ListPostings :many
SELECT p.id, p.owner_id, p.source_id, p.external_id, p.title, p.company, p.url, p.location, p.posted_at,
       p.saved_job_id, p.created_at, s.score, s.reasons, s.scored_by
FROM postings p
LEFT JOIN scores s ON s.posting_id = p.id
WHERE p.owner_id = $1
  AND ($2::real IS NULL OR s.score >= $2::real)
  AND ($3::uuid IS NULL OR p.source_id = $3::uuid)
  AND (
    $4::uuid IS NULL
    OR (COALESCE(s.score, -1)::real, p.id) < ($5::real, $4::uuid)
  )
ORDER BY COALESCE(s.score, -1)::real DESC, p.id DESC
LIMIT $6
`

type ListPostingsParams struct {
	OwnerID    uuid.UUID
	MinScore   *float32
	SourceID   *uuid.UUID
	AfterID    *uuid.UUID
	AfterScore *float32
	RowLimit   int32
}

type ListPostingsRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	SourceID   uuid.UUID
	ExternalID string
	Title      string
	Company    *string
	Url        *string
	Location   *string
	PostedAt   *time.Time
	SavedJobID *uuid.UUID
	CreatedAt  time.Time
	Score      *float32
	Reasons    []byte
	ScoredBy   *string
}

// Best score first, unscored last. Keyset pagination on (score, id), where an
// unscored posting counts as -1; a NULL after_id means the first page.
func (q *Queries) ListPostings(ctx context.Context, arg ListPostingsParams) ([]ListPostingsRow, error) {
	rows, err := q.db.Query(ctx, listPostings,
		arg.OwnerID,
		arg.MinScore,
		arg.SourceID,
		arg.AfterID,
		arg.AfterScore,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostingsRow{}
	for rows.Next() {
		var i ListPostingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.Company,
			&i.Url,
			&i.Location,
			&i.PostedAt,
			&i.SavedJobID,
			&i.CreatedAt,
			&i.Score,
			&i.Reasons,
			&i.ScoredBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscoredPostingIDs = `-- name: ListUnscoredPostingIDs :many
SELECT p.id FROM postings p
LEFT JOIN scores s ON s.posting_id = p.id
WHERE p.source_id = $1 AND s.posting_id IS NULL
ORDER BY p.id
`

func (q *Queries) ListUnscoredPostingIDs(ctx context.Context, sourceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUnscoredPostingIDs, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSavedJob = `-- name: SetSavedJob :one
UPDATE postings SET saved_job_id = $1
WHERE owner_id = $2 AND id = $3 AND saved_job_id IS NULL
RETURNING id, owner_id, source_id, external_id, title, company, url, location, posted_at, raw, saved_job_id, created_at
`

type SetSavedJobParams struct {
	SavedJobID *uuid.UUID
	OwnerID    uuid.UUID
	ID         uuid.UUID
}

// Records the kagami job once; a posting already saved keeps its first job.
func (q *Queries) SetSavedJob(ctx context.Context, arg SetSavedJobParams) (Posting, error) {
	row := q.db.QueryRow(ctx, setSavedJob, arg.SavedJobID, arg.OwnerID, arg.ID)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Location,
		&i.PostedAt,
		&i.Raw,
		&i.SavedJobID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPosting = `-- name: UpsertPosting :one
INSERT INTO postings (id, owner_id, source_id, external_id, title, company, url, location, posted_at, raw, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (source_id, external_id) DO UPDATE SET
    title = EXCLUDED.title, company = EXCLUDED.company, url = EXCLUDED.url,
    location = EXCLUDED.location, posted_at = EXCLUDED.posted_at, raw = EXCLUDED.raw
RETURNING id, owner_id, source_id, external_id, title, company, url, location, posted_at, raw, saved_job_id, created_at,
          (xmax = 0)::boolean AS inserted
`

type UpsertPostingParams struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	SourceID   uuid.UUID
	ExternalID string
	Title      string
	Company    *string
	Url        *string
	Location   *string
	PostedAt   *time.Time
	Raw        []byte
	CreatedAt  time.Time
}

type UpsertPostingRow struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	SourceID   uuid.UUID
	ExternalID string
	Title      string
	Company    *string
	Url        *string
	Location   *string
	PostedAt   *time.Time
	Raw        []byte
	SavedJobID *uuid.UUID
	CreatedAt  time.Time
	Inserted   bool
}

// A posting seen again is refreshed in place; inserted says whether it is new.
func (q *Queries) UpsertPosting(ctx context.Context, arg UpsertPostingParams) (UpsertPostingRow, error) {
	row := q.db.QueryRow(ctx, upsertPosting,
		arg.ID,
		arg.OwnerID,
		arg.SourceID,
		arg.ExternalID,
		arg.Title,
		arg.Company,
		arg.Url,
		arg.Location,
		arg.PostedAt,
		arg.Raw,
		arg.CreatedAt,
	)
	var i UpsertPostingRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SourceID,
		&i.ExternalID,
		&i.Title,
		&i.Company,
		&i.Url,
		&i.Location,
		&i.PostedAt,
		&i.Raw,
		&i.SavedJobID,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}

const upsertScore = `-- name: UpsertScore :exec
INSERT INTO scores (posting_id, score, reasons, scored_by, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (posting_id) DO UPDATE SET
    score = EXCLUDED.score, reasons = EXCLUDED.reasons, scored_by = EXCLUDED.scored_by, created_at = EXCLUDED.created_at
`

type UpsertScoreParams struct {
	PostingID uuid.UUID
	Score     float32
	Reasons   []byte
	ScoredBy  string
	CreatedAt time.Time
}

func (q *Queries) UpsertScore(ctx context.Context, arg UpsertScoreParams) error {
	_, err := q.db.Exec(ctx, upsertScore,
		arg.PostingID,
		arg.Score,
		arg.Reasons,
		arg.ScoredBy,
		arg.CreatedAt,
	)
	return err
}
