// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPreferences = `-- name: GetPreferences :one
SELECT owner_id, roles, locations, must_have, nice_to_have, exclude, min_score, updated_at FROM preferences WHERE owner_id = $1
`

func (q *Queries) GetPreferences(ctx context.Context, ownerID uuid.UUID) (Preference, error) {
	row := q.db.QueryRow(ctx, getPreferences, ownerID)
	var i Preference
	err := row.Scan(
		&i.OwnerID,
		&i.Roles,
		&i.Locations,
		&i.MustHave,
		&i.NiceToHave,
		&i.Exclude,
		&i.MinScore,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :one
INSERT INTO preferences (owner_id, roles, locations, must_have, nice_to_have, exclude, min_score, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (owner_id) DO UPDATE SET
    roles = EXCLUDED.roles, locations = EXCLUDED.locations, must_have = EXCLUDED.must_have,
    nice_to_have = EXCLUDED.nice_to_have, exclude = EXCLUDED.exclude, min_score = EXCLUDED.min_score,
    updated_at = EXCLUDED.updated_at
RETURNING owner_id, roles, locations, must_have, nice_to_have, exclude, min_score, updated_at
`

type UpsertPreferencesParams struct {
	OwnerID    uuid.UUID
	Roles      []string
	Locations  []string
	MustHave   []string
	NiceToHave []string
	Exclude    []string
	MinScore   float32
	UpdatedAt  time.Time
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) (Preference, error) {
	row := q.db.QueryRow(ctx, upsertPreferences,
		arg.OwnerID,
		arg.Roles,
		arg.Locations,
		arg.MustHave,
		arg.NiceToHave,
		arg.Exclude,
		arg.MinScore,
		arg.UpdatedAt,
	)
	var i Preference
	err := row.Scan(
		&i.OwnerID,
		&i.Roles,
		&i.Locations,
		&i.MustHave,
		&i.NiceToHave,
		&i.Exclude,
		&i.MinScore,
		&i.UpdatedAt,
	)
	return i, err
}
