// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getSource = `-- name: GetSource :one
SELECT id, owner_id, name, kind, config, schedule, enabled, last_run_at, last_error FROM sources WHERE owner_id = $1 AND id = $2
`

type GetSourceParams struct {
	OwnerID uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) GetSource(ctx context.Context, arg GetSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, getSource, arg.OwnerID, arg.ID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Schedule,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastError,
	)
	return i, err
}

const insertSource = `-- name: InsertSource :one
INSERT INTO sources (id, owner_id, name, kind, config, schedule, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, name, kind, config, schedule, enabled, last_run_at, last_error
`

type InsertSourceParams struct {
	ID       uuid.UUID
	OwnerID  uuid.UUID
	Name     string
	Kind     string
	Config   []byte
	Schedule string
	Enabled  bool
}

func (q *Queries) InsertSource(ctx context.Context, arg InsertSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, insertSource,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Kind,
		arg.Config,
		arg.Schedule,
		arg.Enabled,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Schedule,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastError,
	)
	return i, err
}

const listEnabledSources = `-- name: ListEnabledSources :many
SELECT id, owner_id, name, kind, config, schedule, enabled, last_run_at, last_error FROM sources WHERE enabled ORDER BY owner_id, id
`

// Every owner's enabled sources, for the scheduler.
func (q *Queries) ListEnabledSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.Query(ctx, listEnabledSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Schedule,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, owner_id, name, kind, config, schedule, enabled, last_run_at, last_error FROM sources WHERE owner_id = $1 ORDER BY name, id
`

func (q *Queries) ListSources(ctx context.Context, ownerID uuid.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSources, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Kind,
			&i.Config,
			&i.Schedule,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSourceRun = `-- name: MarkSourceRun :exec
UPDATE sources SET last_run_at = $1, last_error = $2
WHERE id = $3
`

type MarkSourceRunParams struct {
	LastRunAt *time.Time
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) MarkSourceRun(ctx context.Context, arg MarkSourceRunParams) error {
	_, err := q.db.Exec(ctx, markSourceRun, arg.LastRunAt, arg.LastError, arg.ID)
	return err
}

const updateSource = `-- name: UpdateSource :one
UPDATE sources SET name = $1, config = $2, schedule = $3, enabled = $4
WHERE owner_id = $5 AND id = $6
RETURNING id, owner_id, name, kind, config, schedule, enabled, last_run_at, last_error
`

type UpdateSourceParams struct {
	Name     string
	Config   []byte
	Schedule string
	Enabled  bool
	OwnerID  uuid.UUID
	ID       uuid.UUID
}

// The kind is fixed once a source exists; changing what a source reads would
// leave its old postings under the wrong one.
func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) (Source, error) {
	row := q.db.QueryRow(ctx, updateSource,
		arg.Name,
		arg.Config,
		arg.Schedule,
		arg.Enabled,
		arg.OwnerID,
		arg.ID,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Kind,
		&i.Config,
		&i.Schedule,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastError,
	)
	return i, err
}
