// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const findCompanyByName = `-- name: FindCompanyByName :one
SELECT id, owner_id, name, domain, notes, version, created_at, updated_at, archived_at FROM companies
WHERE owner_id = $1 AND lower(name) = lower($2::text) AND archived_at IS NULL
ORDER BY created_at
LIMIT 1
`

type FindCompanyByNameParams struct {
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) FindCompanyByName(ctx context.Context, arg FindCompanyByNameParams) (Company, error) {
	row := q.db.QueryRow(ctx, findCompanyByName, arg.OwnerID, arg.Name)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domain,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, owner_id, name, domain, notes, version, created_at, updated_at, archived_at FROM companies WHERE id = $1 AND owner_id = $2
`

type GetCompanyParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.ID, arg.OwnerID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domain,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertCompany = `-- name: InsertCompany :one
INSERT INTO companies (id, owner_id, name, domain)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, domain, notes, version, created_at, updated_at, archived_at
`

type InsertCompanyParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
	Domain  *string
}

func (q *Queries) InsertCompany(ctx context.Context, arg InsertCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, insertCompany,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Domain,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domain,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertCompanyByDomain = `-- name: UpsertCompanyByDomain :one
INSERT INTO companies (id, owner_id, name, domain)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, lower(domain)) WHERE domain IS NOT NULL
DO UPDATE SET updated_at = companies.updated_at
RETURNING id, owner_id, name, domain, notes, version, created_at, updated_at, archived_at
`

type UpsertCompanyByDomainParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
	Domain  *string
}

// The domain is the upsert key; a repeat call returns the existing company.
func (q *Queries) UpsertCompanyByDomain(ctx context.Context, arg UpsertCompanyByDomainParams) (Company, error) {
	row := q.db.QueryRow(ctx, upsertCompanyByDomain,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Domain,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Domain,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
