// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const findContactByEmail = `-- name: FindContactByEmail :one
SELECT id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at FROM contacts WHERE owner_id = $1 AND email = $2::citext
`

type FindContactByEmailParams struct {
	OwnerID uuid.UUID
	Email   string
}

// email is citext, so the match ignores case.
func (q *Queries) FindContactByEmail(ctx context.Context, arg FindContactByEmailParams) (Contact, error) {
	row := q.db.QueryRow(ctx, findContactByEmail, arg.OwnerID, arg.Email)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const findContactByLinkedin = `-- name: FindContactByLinkedin :one
SELECT id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at FROM contacts WHERE owner_id = $1 AND linkedin_url = $2::text
`

type FindContactByLinkedinParams struct {
	OwnerID     uuid.UUID
	LinkedinUrl string
}

func (q *Queries) FindContactByLinkedin(ctx context.Context, arg FindContactByLinkedinParams) (Contact, error) {
	row := q.db.QueryRow(ctx, findContactByLinkedin, arg.OwnerID, arg.LinkedinUrl)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at FROM contacts WHERE id = $1 AND owner_id = $2
`

type GetContactParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, arg.ID, arg.OwnerID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getContactByIdempotencyKey = `-- name: GetContactByIdempotencyKey :one
SELECT id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at FROM contacts WHERE owner_id = $1 AND idempotency_key = $2::text
`

type GetContactByIdempotencyKeyParams struct {
	OwnerID        uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetContactByIdempotencyKey(ctx context.Context, arg GetContactByIdempotencyKeyParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByIdempotencyKey, arg.OwnerID, arg.IdempotencyKey)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertContact = `-- name: InsertContact :one
INSERT INTO contacts (
    id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle,
    phone, relationship, how_we_met, status, preferred_channel, last_contacted,
    next_follow_up, target_role, job_id, tags, notes, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20
)
RETURNING id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at
`

type InsertContactParams struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	FullName         string
	CompanyID        *uuid.UUID
	Role             *string
	Email            *string
	LinkedinUrl      *string
	XHandle          *string
	Phone            *string
	Relationship     *string
	HowWeMet         *string
	Status           string
	PreferredChannel *string
	LastContacted    *time.Time
	NextFollowUp     *time.Time
	TargetRole       *string
	JobID            *uuid.UUID
	Tags             []string
	Notes            *string
	IdempotencyKey   *string
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, insertContact,
		arg.ID,
		arg.OwnerID,
		arg.FullName,
		arg.CompanyID,
		arg.Role,
		arg.Email,
		arg.LinkedinUrl,
		arg.XHandle,
		arg.Phone,
		arg.Relationship,
		arg.HowWeMet,
		arg.Status,
		arg.PreferredChannel,
		arg.LastContacted,
		arg.NextFollowUp,
		arg.TargetRole,
		arg.JobID,
		arg.Tags,
		arg.Notes,
		arg.IdempotencyKey,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertContactEvent = `-- name: InsertContactEvent :one
INSERT INTO contact_events (id, contact_id, kind, channel, from_status, to_status, source_event_id, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, contact_id, kind, channel, from_status, to_status, source_event_id, payload, occurred_at
`

type InsertContactEventParams struct {
	ID            uuid.UUID
	ContactID     uuid.UUID
	Kind          string
	Channel       *string
	FromStatus    *string
	ToStatus      *string
	SourceEventID *uuid.UUID
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertContactEvent(ctx context.Context, arg InsertContactEventParams) (ContactEvent, error) {
	row := q.db.QueryRow(ctx, insertContactEvent,
		arg.ID,
		arg.ContactID,
		arg.Kind,
		arg.Channel,
		arg.FromStatus,
		arg.ToStatus,
		arg.SourceEventID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContactEvent
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Kind,
		&i.Channel,
		&i.FromStatus,
		&i.ToStatus,
		&i.SourceEventID,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const listContactEvents = `-- name: ListContactEvents :many
SELECT id, contact_id, kind, channel, from_status, to_status, source_event_id, payload, occurred_at FROM contact_events WHERE contact_id = $1 ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListContactEvents(ctx context.Context, contactID uuid.UUID) ([]ContactEvent, error) {
	rows, err := q.db.Query(ctx, listContactEvents, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactEvent{}
	for rows.Next() {
		var i ContactEvent
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Kind,
			&i.Channel,
			&i.FromStatus,
			&i.ToStatus,
			&i.SourceEventID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.owner_id, c.full_name, c.company_id, c.role, c.email, c.linkedin_url, c.x_handle, c.phone, c.relationship, c.how_we_met, c.status, c.preferred_channel, c.last_contacted, c.next_follow_up, c.target_role, c.job_id, c.tags, c.notes, c.idempotency_key, c.version, c.created_at, c.updated_at, c.archived_at FROM contacts c
LEFT JOIN companies co ON co.id = c.company_id
WHERE c.owner_id = $1
  AND c.archived_at IS NULL
  AND ($2::text IS NULL OR c.status = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY (c.tags))
  AND ($4::uuid IS NULL OR c.company_id = $4::uuid)
  AND (
    $5::text IS NULL
    OR c.full_name ILIKE '%' || $5::text || '%'
    OR c.email::text ILIKE '%' || $5::text || '%'
    OR co.name ILIKE '%' || $5::text || '%'
  )
  AND (
    $6::timestamptz IS NULL
    OR (c.updated_at, c.id) < ($6::timestamptz, $7::uuid)
  )
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $8
`

type ListContactsParams struct {
	OwnerID        uuid.UUID
	Status         *string
	Tag            *string
	CompanyID      *uuid.UUID
	Query          *string
	AfterUpdatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (updated_at, id), newest first.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.OwnerID,
		arg.Status,
		arg.Tag,
		arg.CompanyID,
		arg.Query,
		arg.AfterUpdatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.FullName,
			&i.CompanyID,
			&i.Role,
			&i.Email,
			&i.LinkedinUrl,
			&i.XHandle,
			&i.Phone,
			&i.Relationship,
			&i.HowWeMet,
			&i.Status,
			&i.PreferredChannel,
			&i.LastContacted,
			&i.NextFollowUp,
			&i.TargetRole,
			&i.JobID,
			&i.Tags,
			&i.Notes,
			&i.IdempotencyKey,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET
    full_name = $1,
    company_id = $2,
    role = $3,
    email = $4,
    linkedin_url = $5,
    x_handle = $6,
    phone = $7,
    relationship = $8,
    how_we_met = $9,
    preferred_channel = $10,
    last_contacted = $11,
    next_follow_up = $12,
    target_role = $13,
    job_id = $14,
    tags = $15,
    notes = $16,
    version = version + 1,
    updated_at = now()
WHERE id = $17 AND owner_id = $18 AND version = $19
RETURNING id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at
`

type UpdateContactParams struct {
	FullName         string
	CompanyID        *uuid.UUID
	Role             *string
	Email            *string
	LinkedinUrl      *string
	XHandle          *string
	Phone            *string
	Relationship     *string
	HowWeMet         *string
	PreferredChannel *string
	LastContacted    *time.Time
	NextFollowUp     *time.Time
	TargetRole       *string
	JobID            *uuid.UUID
	Tags             []string
	Notes            *string
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Version          int32
}

// Writes every editable column; the caller applies its field mask to a copy of
// the current row first. Returns no row when the version is stale.
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.FullName,
		arg.CompanyID,
		arg.Role,
		arg.Email,
		arg.LinkedinUrl,
		arg.XHandle,
		arg.Phone,
		arg.Relationship,
		arg.HowWeMet,
		arg.PreferredChannel,
		arg.LastContacted,
		arg.NextFollowUp,
		arg.TargetRole,
		arg.JobID,
		arg.Tags,
		arg.Notes,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateContactStatus = `-- name: UpdateContactStatus :one
UPDATE contacts SET
    status = $1,
    last_contacted = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3 AND owner_id = $4 AND version = $5
RETURNING id, owner_id, full_name, company_id, role, email, linkedin_url, x_handle, phone, relationship, how_we_met, status, preferred_channel, last_contacted, next_follow_up, target_role, job_id, tags, notes, idempotency_key, version, created_at, updated_at, archived_at
`

type UpdateContactStatusParams struct {
	Status        string
	LastContacted *time.Time
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Version       int32
}

func (q *Queries) UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContactStatus,
		arg.Status,
		arg.LastContacted,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.FullName,
		&i.CompanyID,
		&i.Role,
		&i.Email,
		&i.LinkedinUrl,
		&i.XHandle,
		&i.Phone,
		&i.Relationship,
		&i.HowWeMet,
		&i.Status,
		&i.PreferredChannel,
		&i.LastContacted,
		&i.NextFollowUp,
		&i.TargetRole,
		&i.JobID,
		&i.Tags,
		&i.Notes,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
