// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: imports.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertImport = `-- name: InsertImport :one
INSERT INTO imports (id, owner_id, filename, rows_total, rows_created, rows_updated, rows_failed, errors)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, owner_id, filename, rows_total, rows_created, rows_updated, rows_failed, errors, created_at
`

type InsertImportParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Filename    string
	RowsTotal   int32
	RowsCreated int32
	RowsUpdated int32
	RowsFailed  int32
	Errors      []byte
}

func (q *Queries) InsertImport(ctx context.Context, arg InsertImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, insertImport,
		arg.ID,
		arg.OwnerID,
		arg.Filename,
		arg.RowsTotal,
		arg.RowsCreated,
		arg.RowsUpdated,
		arg.RowsFailed,
		arg.Errors,
	)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.RowsTotal,
		&i.RowsCreated,
		&i.RowsUpdated,
		&i.RowsFailed,
		&i.Errors,
		&i.CreatedAt,
	)
	return i, err
}
