// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getJob = `-- name: GetJob :one
SELECT id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at FROM jobs WHERE id = $1 AND owner_id = $2
`

type GetJobParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, arg.ID, arg.OwnerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at FROM jobs WHERE owner_id = $1 AND idempotency_key = $2::text
`

type GetJobByIdempotencyKeyParams struct {
	OwnerID        uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.OwnerID, arg.IdempotencyKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getJobByURL = `-- name: GetJobByURL :one
SELECT id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at FROM jobs WHERE owner_id = $1 AND url = $2::text
`

type GetJobByURLParams struct {
	OwnerID uuid.UUID
	Url     string
}

func (q *Queries) GetJobByURL(ctx context.Context, arg GetJobByURLParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByURL, arg.OwnerID, arg.Url)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    id, owner_id, company_id, title, url, source, status, applied_on,
    next_follow_up, location, salary_text, description, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at
`

type InsertJobParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	CompanyID      uuid.UUID
	Title          string
	Url            *string
	Source         string
	Status         string
	AppliedOn      *time.Time
	NextFollowUp   *time.Time
	Location       *string
	SalaryText     *string
	Description    *string
	IdempotencyKey *string
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.ID,
		arg.OwnerID,
		arg.CompanyID,
		arg.Title,
		arg.Url,
		arg.Source,
		arg.Status,
		arg.AppliedOn,
		arg.NextFollowUp,
		arg.Location,
		arg.SalaryText,
		arg.Description,
		arg.IdempotencyKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertJobEvent = `-- name: InsertJobEvent :one
INSERT INTO job_events (id, job_id, kind, from_status, to_status, source_event_id, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, job_id, kind, from_status, to_status, source_event_id, payload, occurred_at
`

type InsertJobEventParams struct {
	ID            uuid.UUID
	JobID         uuid.UUID
	Kind          string
	FromStatus    *string
	ToStatus      *string
	SourceEventID *uuid.UUID
	Payload       []byte
	OccurredAt    time.Time
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, insertJobEvent,
		arg.ID,
		arg.JobID,
		arg.Kind,
		arg.FromStatus,
		arg.ToStatus,
		arg.SourceEventID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Kind,
		&i.FromStatus,
		&i.ToStatus,
		&i.SourceEventID,
		&i.Payload,
		&i.OccurredAt,
	)
	return i, err
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT id, job_id, kind, from_status, to_status, source_event_id, payload, occurred_at FROM job_events WHERE job_id = $1 ORDER BY occurred_at DESC, id DESC
`

func (q *Queries) ListJobEvents(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobEvent{}
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Kind,
			&i.FromStatus,
			&i.ToStatus,
			&i.SourceEventID,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at FROM jobs
WHERE owner_id = $1
  AND archived_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::uuid IS NULL OR company_id = $3::uuid)
  AND ($4::date IS NULL OR next_follow_up <= $4::date)
  AND (
    $5::timestamptz IS NULL
    OR (updated_at, id) < ($5::timestamptz, $6::uuid)
  )
ORDER BY updated_at DESC, id DESC
LIMIT $7
`

type ListJobsParams struct {
	OwnerID        uuid.UUID
	Status         *string
	CompanyID      *uuid.UUID
	DueBefore      *time.Time
	AfterUpdatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

// Keyset pagination on (updated_at, id), newest first. A NULL after_* pair
// means the first page.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.OwnerID,
		arg.Status,
		arg.CompanyID,
		arg.DueBefore,
		arg.AfterUpdatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CompanyID,
			&i.Title,
			&i.Url,
			&i.Source,
			&i.Status,
			&i.AppliedOn,
			&i.NextFollowUp,
			&i.Location,
			&i.SalaryText,
			&i.Description,
			&i.IdempotencyKey,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs SET
    title = $1,
    url = $2,
    source = $3,
    applied_on = $4,
    next_follow_up = $5,
    location = $6,
    salary_text = $7,
    description = $8,
    version = version + 1,
    updated_at = now()
WHERE id = $9 AND owner_id = $10 AND version = $11
RETURNING id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at
`

type UpdateJobParams struct {
	Title        string
	Url          *string
	Source       string
	AppliedOn    *time.Time
	NextFollowUp *time.Time
	Location     *string
	SalaryText   *string
	Description  *string
	ID           uuid.UUID
	OwnerID      uuid.UUID
	Version      int32
}

// Writes every editable column; the caller applies its field mask to a copy of
// the current row first. Returns no row when the version is stale.
func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.Title,
		arg.Url,
		arg.Source,
		arg.AppliedOn,
		arg.NextFollowUp,
		arg.Location,
		arg.SalaryText,
		arg.Description,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs SET
    status = $1,
    applied_on = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3 AND owner_id = $4 AND version = $5
RETURNING id, owner_id, company_id, title, url, source, status, applied_on, next_follow_up, location, salary_text, description, idempotency_key, version, created_at, updated_at, archived_at
`

type UpdateJobStatusParams struct {
	Status    string
	AppliedOn *time.Time
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Version   int32
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.Status,
		arg.AppliedOn,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CompanyID,
		&i.Title,
		&i.Url,
		&i.Source,
		&i.Status,
		&i.AppliedOn,
		&i.NextFollowUp,
		&i.Location,
		&i.SalaryText,
		&i.Description,
		&i.IdempotencyKey,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
