// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	Name       string
	Domain     *string
	Notes      *string
	Version    int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

type Contact struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	FullName         string
	CompanyID        *uuid.UUID
	Role             *string
	Email            *string
	LinkedinUrl      *string
	XHandle          *string
	Phone            *string
	Relationship     *string
	HowWeMet         *string
	Status           string
	PreferredChannel *string
	LastContacted    *time.Time
	NextFollowUp     *time.Time
	TargetRole       *string
	JobID            *uuid.UUID
	Tags             []string
	Notes            *string
	IdempotencyKey   *string
	Version          int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ArchivedAt       *time.Time
}

type ContactEvent struct {
	ID            uuid.UUID
	ContactID     uuid.UUID
	Kind          string
	Channel       *string
	FromStatus    *string
	ToStatus      *string
	SourceEventID *uuid.UUID
	Payload       []byte
	OccurredAt    time.Time
}

type Import struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Filename    string
	RowsTotal   int32
	RowsCreated int32
	RowsUpdated int32
	RowsFailed  int32
	Errors      []byte
	CreatedAt   time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Job struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	CompanyID      uuid.UUID
	Title          string
	Url            *string
	Source         string
	Status         string
	AppliedOn      *time.Time
	NextFollowUp   *time.Time
	Location       *string
	SalaryText     *string
	Description    *string
	IdempotencyKey *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
}

type JobEvent struct {
	ID            uuid.UUID
	JobID         uuid.UUID
	Kind          string
	FromStatus    *string
	ToStatus      *string
	SourceEventID *uuid.UUID
	Payload       []byte
	OccurredAt    time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}
