// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLedgerEntryByReservation = `-- name: GetLedgerEntryByReservation :one
SELECT id, owner_id, reservation_id, service, feature, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_micros, request_id, occurred_at FROM ledger WHERE reservation_id = $1
`

func (q *Queries) GetLedgerEntryByReservation(ctx context.Context, reservationID uuid.UUID) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedgerEntryByReservation, reservationID)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ReservationID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CostMicros,
		&i.RequestID,
		&i.OccurredAt,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger (id, owner_id, reservation_id, service, feature, model, input_tokens, output_tokens,
                    cache_read_tokens, cache_write_tokens, cost_micros, request_id, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11, $12, $13)
RETURNING id, owner_id, reservation_id, service, feature, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_micros, request_id, occurred_at
`

type InsertLedgerEntryParams struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	ReservationID    uuid.UUID
	Service          string
	Feature          string
	Model            string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostMicros       int64
	RequestID        *string
	OccurredAt       time.Time
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.OwnerID,
		arg.ReservationID,
		arg.Service,
		arg.Feature,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostMicros,
		arg.RequestID,
		arg.OccurredAt,
	)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ReservationID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CostMicros,
		&i.RequestID,
		&i.OccurredAt,
	)
	return i, err
}

const sumSpend = `-- name: SumSpend :many
SELECT (CASE $1::text
          WHEN 'service' THEN service
          WHEN 'feature' THEN feature
          WHEN 'model' THEN model
          ELSE to_char(occurred_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD')
        END)::text AS key,
       sum(cost_micros)::bigint AS cost_micros,
       sum(input_tokens)::bigint AS input_tokens,
       sum(output_tokens)::bigint AS output_tokens,
       sum(cache_read_tokens)::bigint AS cache_read_tokens,
       sum(cache_write_tokens)::bigint AS cache_write_tokens
FROM ledger
WHERE owner_id = $2 AND occurred_at >= $3 AND occurred_at < $4
GROUP BY 1
ORDER BY 1
`

type SumSpendParams struct {
	GroupBy  string
	OwnerID  uuid.UUID
	FromTime time.Time
	ToTime   time.Time
}

type SumSpendRow struct {
	Key              string
	CostMicros       int64
	InputTokens      int64
	OutputTokens     int64
	CacheReadTokens  int64
	CacheWriteTokens int64
}

// group_by is service, feature, model or day; a day is an Asia/Kolkata date.
func (q *Queries) SumSpend(ctx context.Context, arg SumSpendParams) ([]SumSpendRow, error) {
	rows, err := q.db.Query(ctx, sumSpend,
		arg.GroupBy,
		arg.OwnerID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumSpendRow{}
	for rows.Next() {
		var i SumSpendRow
		if err := rows.Scan(
			&i.Key,
			&i.CostMicros,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
