// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Budget struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	ScopeType   string
	ScopeValue  string
	Period      string
	LimitMicros int64
	Mode        string
	Thresholds  []int32
	Enabled     bool
	Version     int32
	UpdatedAt   time.Time
}

type BudgetPeriod struct {
	ID                 uuid.UUID
	BudgetID           uuid.UUID
	PeriodStart        time.Time
	PeriodEnd          time.Time
	SpentMicros        int64
	ReservedMicros     int64
	NotifiedThresholds []int32
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Ledger struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	ReservationID    uuid.UUID
	Service          string
	Feature          string
	Model            string
	InputTokens      int32
	OutputTokens     int32
	CacheReadTokens  int32
	CacheWriteTokens int32
	CostMicros       int64
	RequestID        *string
	OccurredAt       time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Price struct {
	Model                   string
	EffectiveFrom           time.Time
	InputMicrosPerMtok      int64
	OutputMicrosPerMtok     int64
	CacheReadMicrosPerMtok  int64
	CacheWriteMicrosPerMtok int64
}

type Reservation struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Service         string
	Feature         string
	Model           string
	EstMicros       int64
	BudgetPeriodIds []uuid.UUID
	Status          string
	CreatedAt       time.Time
	ExpiresAt       time.Time
}
