// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: periods.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReserved = `-- name: AddReserved :exec
UPDATE budget_periods SET reserved_micros = reserved_micros + $1 WHERE id = $2
`

type AddReservedParams struct {
	Delta int64
	ID    uuid.UUID
}

func (q *Queries) AddReserved(ctx context.Context, arg AddReservedParams) error {
	_, err := q.db.Exec(ctx, addReserved, arg.Delta, arg.ID)
	return err
}

const insertPeriodIfAbsent = `-- name: InsertPeriodIfAbsent :exec
INSERT INTO budget_periods (id, budget_id, period_start, period_end)
VALUES ($1, $2, $3, $4)
ON CONFLICT (budget_id, period_start) DO NOTHING
`

type InsertPeriodIfAbsentParams struct {
	ID          uuid.UUID
	BudgetID    uuid.UUID
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) InsertPeriodIfAbsent(ctx context.Context, arg InsertPeriodIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertPeriodIfAbsent,
		arg.ID,
		arg.BudgetID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	return err
}

const lockPeriod = `-- name: LockPeriod :one
SELECT id, budget_id, period_start, period_end, spent_micros, reserved_micros, notified_thresholds FROM budget_periods
WHERE budget_id = $1 AND period_start = $2
FOR UPDATE
`

type LockPeriodParams struct {
	BudgetID    uuid.UUID
	PeriodStart time.Time
}

func (q *Queries) LockPeriod(ctx context.Context, arg LockPeriodParams) (BudgetPeriod, error) {
	row := q.db.QueryRow(ctx, lockPeriod, arg.BudgetID, arg.PeriodStart)
	var i BudgetPeriod
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.SpentMicros,
		&i.ReservedMicros,
		&i.NotifiedThresholds,
	)
	return i, err
}

const lockPeriodsByID = `-- name: LockPeriodsByID :many
SELECT id, budget_id, period_start, period_end, spent_micros, reserved_micros, notified_thresholds FROM budget_periods WHERE id = ANY ($1::uuid[]) ORDER BY budget_id FOR UPDATE
`

// Ordered by budget id, the order Reserve locks in, so the two cannot deadlock.
func (q *Queries) LockPeriodsByID(ctx context.Context, ids []uuid.UUID) ([]BudgetPeriod, error) {
	rows, err := q.db.Query(ctx, lockPeriodsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetPeriod{}
	for rows.Next() {
		var i BudgetPeriod
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.SpentMicros,
			&i.ReservedMicros,
			&i.NotifiedThresholds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markThresholdNotified = `-- name: MarkThresholdNotified :exec
UPDATE budget_periods
SET notified_thresholds = array_append(notified_thresholds, $1::int)
WHERE id = $2 AND NOT ($1::int = ANY (notified_thresholds))
`

type MarkThresholdNotifiedParams struct {
	Threshold int32
	ID        uuid.UUID
}

func (q *Queries) MarkThresholdNotified(ctx context.Context, arg MarkThresholdNotifiedParams) error {
	_, err := q.db.Exec(ctx, markThresholdNotified, arg.Threshold, arg.ID)
	return err
}

const settlePeriod = `-- name: SettlePeriod :exec
UPDATE budget_periods
SET reserved_micros = reserved_micros - $1,
    spent_micros = spent_micros + $2
WHERE id = $3
`

type SettlePeriodParams struct {
	ReleaseMicros int64
	SpendMicros   int64
	ID            uuid.UUID
}

func (q *Queries) SettlePeriod(ctx context.Context, arg SettlePeriodParams) error {
	_, err := q.db.Exec(ctx, settlePeriod, arg.ReleaseMicros, arg.SpendMicros, arg.ID)
	return err
}
