// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"
	"time"
)

const getPriceOn = `-- name: GetPriceOn :one
SELECT model, effective_from, input_micros_per_mtok, output_micros_per_mtok, cache_read_micros_per_mtok, cache_write_micros_per_mtok FROM prices
WHERE model = $1 AND effective_from <= $2
ORDER BY effective_from DESC
LIMIT 1
`

type GetPriceOnParams struct {
	Model  string
	OnDate time.Time
}

// The price in force on a date: the latest one effective on or before it.
func (q *Queries) GetPriceOn(ctx context.Context, arg GetPriceOnParams) (Price, error) {
	row := q.db.QueryRow(ctx, getPriceOn, arg.Model, arg.OnDate)
	var i Price
	err := row.Scan(
		&i.Model,
		&i.EffectiveFrom,
		&i.InputMicrosPerMtok,
		&i.OutputMicrosPerMtok,
		&i.CacheReadMicrosPerMtok,
		&i.CacheWriteMicrosPerMtok,
	)
	return i, err
}
