// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (id, owner_id, service, feature, model, est_micros, budget_period_ids, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, service, feature, model, est_micros, budget_period_ids, status, created_at, expires_at
`

type InsertReservationParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Service         string
	Feature         string
	Model           string
	EstMicros       int64
	BudgetPeriodIds []uuid.UUID
	CreatedAt       time.Time
	ExpiresAt       time.Time
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ID,
		arg.OwnerID,
		arg.Service,
		arg.Feature,
		arg.Model,
		arg.EstMicros,
		arg.BudgetPeriodIds,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.EstMicros,
		&i.BudgetPeriodIds,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listExpiredReservationIDs = `-- name: ListExpiredReservationIDs :many
SELECT id FROM reservations
WHERE status = 'open' AND expires_at <= $1
ORDER BY expires_at
LIMIT $2
`

type ListExpiredReservationIDsParams struct {
	Now       time.Time
	BatchSize int32
}

func (q *Queries) ListExpiredReservationIDs(ctx context.Context, arg ListExpiredReservationIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredReservationIDs, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReservation = `-- name: LockReservation :one
SELECT id, owner_id, service, feature, model, est_micros, budget_period_ids, status, created_at, expires_at FROM reservations WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type LockReservationParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) LockReservation(ctx context.Context, arg LockReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, lockReservation, arg.ID, arg.OwnerID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.EstMicros,
		&i.BudgetPeriodIds,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const lockReservationByID = `-- name: LockReservationByID :one
SELECT id, owner_id, service, feature, model, est_micros, budget_period_ids, status, created_at, expires_at FROM reservations WHERE id = $1 FOR UPDATE
`

// For the sweeper, which acts for no owner.
func (q *Queries) LockReservationByID(ctx context.Context, id uuid.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, lockReservationByID, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.EstMicros,
		&i.BudgetPeriodIds,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setReservationStatus = `-- name: SetReservationStatus :exec
UPDATE reservations SET status = $1 WHERE id = $2
`

type SetReservationStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) SetReservationStatus(ctx context.Context, arg SetReservationStatusParams) error {
	_, err := q.db.Exec(ctx, setReservationStatus, arg.Status, arg.ID)
	return err
}
