// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (id, owner_id, service, feature, model, est_micros, budget_period_ids, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, owner_id, service, feature, model, est_micros, budget_period_ids, status, created_at, expires_at
`

type InsertReservationParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Service         string
	Feature         string
	Model           string
	EstMicros       int64
	BudgetPeriodIds []uuid.UUID
	CreatedAt       time.Time
	ExpiresAt       time.Time
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.ID,
		arg.OwnerID,
		arg.Service,
		arg.Feature,
		arg.Model,
		arg.EstMicros,
		arg.BudgetPeriodIds,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Service,
		&i.Feature,
		&i.Model,
		&i.EstMicros,
		&i.BudgetPeriodIds,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
