// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, owner_id, provider, address, token_ciphertext, token_key_id, history_id, status, last_synced_at, created_at, updated_at FROM accounts WHERE id = $1 AND owner_id = $2
`

type GetAccountParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.OwnerID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Address,
		&i.TokenCiphertext,
		&i.TokenKeyID,
		&i.HistoryID,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner_id, provider, address, token_ciphertext, token_key_id, history_id, status, last_synced_at, created_at, updated_at FROM accounts WHERE owner_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListAccounts(ctx context.Context, ownerID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Provider,
			&i.Address,
			&i.TokenCiphertext,
			&i.TokenKeyID,
			&i.HistoryID,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO accounts (id, owner_id, provider, address, token_ciphertext, token_key_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (owner_id, provider, address) DO UPDATE SET
    token_ciphertext = EXCLUDED.token_ciphertext,
    token_key_id = EXCLUDED.token_key_id,
    status = 'active',
    updated_at = now()
RETURNING id, owner_id, provider, address, token_ciphertext, token_key_id, history_id, status, last_synced_at, created_at, updated_at
`

type UpsertAccountParams struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Provider        string
	Address         string
	TokenCiphertext []byte
	TokenKeyID      string
}

// Connecting an address again replaces its token and clears a reauth or
// disabled status; its sync cursor is kept.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.ID,
		arg.OwnerID,
		arg.Provider,
		arg.Address,
		arg.TokenCiphertext,
		arg.TokenKeyID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Provider,
		&i.Address,
		&i.TokenCiphertext,
		&i.TokenKeyID,
		&i.HistoryID,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
