// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMessage = `-- name: GetMessage :one
SELECT id, owner_id, account_id, provider_message_id, provider_thread_id, direction, from_addr, to_addrs, subject, snippet, received_at, classification, confidence, classified_by, linked_job_id, linked_contact_id, created_at FROM messages WHERE id = $1 AND owner_id = $2
`

type GetMessageParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.OwnerID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccountID,
		&i.ProviderMessageID,
		&i.ProviderThreadID,
		&i.Direction,
		&i.FromAddr,
		&i.ToAddrs,
		&i.Subject,
		&i.Snippet,
		&i.ReceivedAt,
		&i.Classification,
		&i.Confidence,
		&i.ClassifiedBy,
		&i.LinkedJobID,
		&i.LinkedContactID,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    id, owner_id, account_id, provider_message_id, provider_thread_id, direction,
    from_addr, to_addrs, subject, snippet, received_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
ON CONFLICT (account_id, provider_message_id) DO NOTHING
RETURNING id, owner_id, account_id, provider_message_id, provider_thread_id, direction, from_addr, to_addrs, subject, snippet, received_at, classification, confidence, classified_by, linked_job_id, linked_contact_id, created_at
`

type InsertMessageParams struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	AccountID         uuid.UUID
	ProviderMessageID string
	ProviderThreadID  *string
	Direction         string
	FromAddr          string
	ToAddrs           []string
	Subject           *string
	Snippet           *string
	ReceivedAt        time.Time
}

// A message already stored (same account and provider id) returns no row.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.OwnerID,
		arg.AccountID,
		arg.ProviderMessageID,
		arg.ProviderThreadID,
		arg.Direction,
		arg.FromAddr,
		arg.ToAddrs,
		arg.Subject,
		arg.Snippet,
		arg.ReceivedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccountID,
		&i.ProviderMessageID,
		&i.ProviderThreadID,
		&i.Direction,
		&i.FromAddr,
		&i.ToAddrs,
		&i.Subject,
		&i.Snippet,
		&i.ReceivedAt,
		&i.Classification,
		&i.Confidence,
		&i.ClassifiedBy,
		&i.LinkedJobID,
		&i.LinkedContactID,
		&i.CreatedAt,
	)
	return i, err
}
