// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	Provider        string
	Address         string
	TokenCiphertext []byte
	TokenKeyID      string
	HistoryID       *string
	Status          string
	LastSyncedAt    *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Message struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	AccountID         uuid.UUID
	ProviderMessageID string
	ProviderThreadID  *string
	Direction         string
	FromAddr          string
	ToAddrs           []string
	Subject           *string
	Snippet           *string
	ReceivedAt        time.Time
	Classification    *string
	Confidence        *float32
	ClassifiedBy      *string
	LinkedJobID       *uuid.UUID
	LinkedContactID   *uuid.UUID
	CreatedAt         time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Send struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	AccountID         uuid.UUID
	DraftID           uuid.UUID
	DraftVersion      int32
	TokenJti          uuid.UUID
	ToAddrs           []string
	ProviderMessageID *string
	Status            string
	Error             *string
	CreatedAt         time.Time
	SentAt            *time.Time
}
