// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sends.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertSend = `-- name: InsertSend :one
INSERT INTO sends (
    id, owner_id, account_id, draft_id, draft_version, contact_id, job_id, token_jti, to_addrs, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, 'sending'
)
RETURNING id, owner_id, account_id, draft_id, draft_version, token_jti, to_addrs, provider_message_id, status, error, created_at, sent_at, contact_id, job_id
`

type InsertSendParams struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	AccountID    uuid.UUID
	DraftID      uuid.UUID
	DraftVersion int32
	ContactID    *uuid.UUID
	JobID        *uuid.UUID
	TokenJti     uuid.UUID
	ToAddrs      []string
}

// The unique token_jti is what makes a Hanko single use: a second insert with
// the same token fails.
func (q *Queries) InsertSend(ctx context.Context, arg InsertSendParams) (Send, error) {
	row := q.db.QueryRow(ctx, insertSend,
		arg.ID,
		arg.OwnerID,
		arg.AccountID,
		arg.DraftID,
		arg.DraftVersion,
		arg.ContactID,
		arg.JobID,
		arg.TokenJti,
		arg.ToAddrs,
	)
	var i Send
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AccountID,
		&i.DraftID,
		&i.DraftVersion,
		&i.TokenJti,
		&i.ToAddrs,
		&i.ProviderMessageID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.SentAt,
		&i.ContactID,
		&i.JobID,
	)
	return i, err
}

const listOpenSends = `-- name: ListOpenSends :many
SELECT id, owner_id, account_id, draft_id, draft_version, token_jti, to_addrs, provider_message_id, status, error, created_at, sent_at, contact_id, job_id FROM sends WHERE status = 'sending' AND created_at <= $1 ORDER BY created_at, id LIMIT $2
`

type ListOpenSendsParams struct {
	StartedBefore time.Time
	RowLimit      int32
}

// Sends that were started and never finished, oldest first.
func (q *Queries) ListOpenSends(ctx context.Context, arg ListOpenSendsParams) ([]Send, error) {
	rows, err := q.db.Query(ctx, listOpenSends, arg.StartedBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Send{}
	for rows.Next() {
		var i Send
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AccountID,
			&i.DraftID,
			&i.DraftVersion,
			&i.TokenJti,
			&i.ToAddrs,
			&i.ProviderMessageID,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
			&i.SentAt,
			&i.ContactID,
			&i.JobID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSendFailed = `-- name: MarkSendFailed :execrows
UPDATE sends SET status = 'failed', error = $1
WHERE id = $2 AND status = 'sending'
`

type MarkSendFailedParams struct {
	Error *string
	ID    uuid.UUID
}

func (q *Queries) MarkSendFailed(ctx context.Context, arg MarkSendFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSendFailed, arg.Error, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSendSent = `-- name: MarkSendSent :execrows
UPDATE sends SET status = 'sent', provider_message_id = $1, sent_at = $2, error = NULL
WHERE id = $3 AND status = 'sending'
`

type MarkSendSentParams struct {
	ProviderMessageID *string
	SentAt            *time.Time
	ID                uuid.UUID
}

func (q *Queries) MarkSendSent(ctx context.Context, arg MarkSendSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSendSent, arg.ProviderMessageID, arg.SentAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
