apiVersion: v2
name: shogun-katana
description: The katana service.
type: application
version: 0.1.0
appVersion: "0.0.0"
dependencies:
  - name: shogun-service
    version: 0.1.0
    repository: file://../service
