apiVersion: v1
kind: Service
metadata:
  name: {{ include "shogunPostgres.fullname" . }}
  labels:
    {{- include "shogunPostgres.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "shogunPostgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
