// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertApproval = `-- name: InsertApproval :one
INSERT INTO approvals (id, draft_id, version, token_jti, approved_by, approved_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, draft_id, version, token_jti, approved_by, approved_at, expires_at
`

type InsertApprovalParams struct {
	ID         uuid.UUID
	DraftID    uuid.UUID
	Version    int32
	TokenJti   uuid.UUID
	ApprovedBy uuid.UUID
	ApprovedAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, insertApproval,
		arg.ID,
		arg.DraftID,
		arg.Version,
		arg.TokenJti,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.ExpiresAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.DraftID,
		&i.Version,
		&i.TokenJti,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ExpiresAt,
	)
	return i, err
}
