// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getDraft = `-- name: GetDraft :one
SELECT id, owner_id, kind, target_type, target_id, channel, state, current_version, recipient, failure_reason, version, created_at, updated_at, idempotency_key FROM drafts WHERE id = $1 AND owner_id = $2
`

type GetDraftParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.ID, arg.OwnerID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.Channel,
		&i.State,
		&i.CurrentVersion,
		&i.Recipient,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getDraftByIdempotencyKey = `-- name: GetDraftByIdempotencyKey :one
SELECT id, owner_id, kind, target_type, target_id, channel, state, current_version, recipient, failure_reason, version, created_at, updated_at, idempotency_key FROM drafts WHERE owner_id = $1 AND idempotency_key = $2::text
`

type GetDraftByIdempotencyKeyParams struct {
	OwnerID        uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetDraftByIdempotencyKey(ctx context.Context, arg GetDraftByIdempotencyKeyParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraftByIdempotencyKey, arg.OwnerID, arg.IdempotencyKey)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.Channel,
		&i.State,
		&i.CurrentVersion,
		&i.Recipient,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const insertDraft = `-- name: InsertDraft :one
INSERT INTO drafts (
    id, owner_id, kind, target_type, target_id, channel, recipient, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, owner_id, kind, target_type, target_id, channel, state, current_version, recipient, failure_reason, version, created_at, updated_at, idempotency_key
`

type InsertDraftParams struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Kind           string
	TargetType     string
	TargetID       *uuid.UUID
	Channel        string
	Recipient      *string
	IdempotencyKey *string
}

func (q *Queries) InsertDraft(ctx context.Context, arg InsertDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, insertDraft,
		arg.ID,
		arg.OwnerID,
		arg.Kind,
		arg.TargetType,
		arg.TargetID,
		arg.Channel,
		arg.Recipient,
		arg.IdempotencyKey,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.Channel,
		&i.State,
		&i.CurrentVersion,
		&i.Recipient,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT d.id, d.owner_id, d.kind, d.target_type, d.target_id, d.channel, d.state, d.current_version, d.recipient, d.failure_reason, d.version, d.created_at, d.updated_at, d.idempotency_key, v.subject AS version_subject, COALESCE(left(v.body, 200), '')::text AS version_preview
FROM drafts d
LEFT JOIN draft_versions v ON v.draft_id = d.id AND v.version = d.current_version
WHERE d.owner_id = $1
  AND d.state = $2::text
  AND (
    $3::timestamptz IS NULL
    OR (d.updated_at, d.id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY d.updated_at DESC, d.id DESC
LIMIT $5
`

type ListDraftsParams struct {
	OwnerID        uuid.UUID
	State          string
	AfterUpdatedAt *time.Time
	AfterID        *uuid.UUID
	RowLimit       int32
}

type ListDraftsRow struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Kind           string
	TargetType     string
	TargetID       *uuid.UUID
	Channel        string
	State          string
	CurrentVersion int32
	Recipient      *string
	FailureReason  *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IdempotencyKey *string
	VersionSubject *string
	VersionPreview string
}

// Keyset pagination on (updated_at, id), newest first. A NULL after_* pair
// means the first page. Each draft carries the subject and the start of the
// body of its newest version, so the queue can be shown without a call each.
func (q *Queries) ListDrafts(ctx context.Context, arg ListDraftsParams) ([]ListDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDrafts,
		arg.OwnerID,
		arg.State,
		arg.AfterUpdatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftsRow{}
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Kind,
			&i.TargetType,
			&i.TargetID,
			&i.Channel,
			&i.State,
			&i.CurrentVersion,
			&i.Recipient,
			&i.FailureReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.VersionSubject,
			&i.VersionPreview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDraftRecipient = `-- name: SetDraftRecipient :execrows
UPDATE drafts SET recipient = $1
WHERE id = $2 AND owner_id = $3 AND recipient IS NULL
`

type SetDraftRecipientParams struct {
	Recipient *string
	ID        uuid.UUID
	OwnerID   uuid.UUID
}

// Fills in the recipient of a draft that has none; a recipient the owner gave
// is never replaced.
func (q *Queries) SetDraftRecipient(ctx context.Context, arg SetDraftRecipientParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDraftRecipient, arg.Recipient, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftState = `-- name: UpdateDraftState :one
UPDATE drafts SET
    state = $1,
    current_version = $2,
    failure_reason = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $4 AND owner_id = $5 AND version = $6
RETURNING id, owner_id, kind, target_type, target_id, channel, state, current_version, recipient, failure_reason, version, created_at, updated_at, idempotency_key
`

type UpdateDraftStateParams struct {
	State          string
	CurrentVersion int32
	FailureReason  *string
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Version        int32
}

// Writes the state, newest version and failure reason. Returns no row when the
// version is stale.
func (q *Queries) UpdateDraftState(ctx context.Context, arg UpdateDraftStateParams) (Draft, error) {
	row := q.db.QueryRow(ctx, updateDraftState,
		arg.State,
		arg.CurrentVersion,
		arg.FailureReason,
		arg.ID,
		arg.OwnerID,
		arg.Version,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.TargetType,
		&i.TargetID,
		&i.Channel,
		&i.State,
		&i.CurrentVersion,
		&i.Recipient,
		&i.FailureReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
