// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

type Approval struct {
	ID         uuid.UUID
	DraftID    uuid.UUID
	Version    int32
	TokenJti   uuid.UUID
	ApprovedBy uuid.UUID
	ApprovedAt time.Time
	ExpiresAt  time.Time
}

type Draft struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Kind           string
	TargetType     string
	TargetID       *uuid.UUID
	Channel        string
	State          string
	CurrentVersion int32
	Recipient      *string
	FailureReason  *string
	Version        int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IdempotencyKey *string
}

type DraftVersion struct {
	DraftID       uuid.UUID
	Version       int32
	Subject       *string
	Body          string
	BodySha256    []byte
	ExtraContext  *string
	PromptContext []byte
	Model         *string
	ReservationID *uuid.UUID
	CreatedBy     string
	CreatedAt     time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}

type Template struct {
	ID            uuid.UUID
	OwnerID       uuid.UUID
	Kind          string
	ContactStatus *string
	Channel       string
	Instructions  string
	Version       int32
	UpdatedAt     time.Time
}

type VoiceSample struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Channel   string
	Text      string
	Embedding *pgvector.Vector
	CreatedAt time.Time
}
