// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTemplate = `-- name: GetTemplate :one
SELECT id, owner_id, kind, contact_status, channel, instructions, version, updated_at FROM templates
WHERE owner_id = $1 AND kind = $2 AND channel = $3
  AND contact_status IS NOT DISTINCT FROM $4::text
`

type GetTemplateParams struct {
	OwnerID       uuid.UUID
	Kind          string
	Channel       string
	ContactStatus *string
}

// contact_status is NULL for templates that are not tied to a contact status.
func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate,
		arg.OwnerID,
		arg.Kind,
		arg.Channel,
		arg.ContactStatus,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Kind,
		&i.ContactStatus,
		&i.Channel,
		&i.Instructions,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
