// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: versions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertDraftVersion = `-- name: InsertDraftVersion :one
INSERT INTO draft_versions (
    draft_id, version, subject, body, body_sha256, extra_context, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING draft_id, version, subject, body, body_sha256, extra_context, prompt_context, model, reservation_id, created_by, created_at
`

type InsertDraftVersionParams struct {
	DraftID      uuid.UUID
	Version      int32
	Subject      *string
	Body         string
	BodySha256   []byte
	ExtraContext *string
	CreatedBy    string
}

func (q *Queries) InsertDraftVersion(ctx context.Context, arg InsertDraftVersionParams) (DraftVersion, error) {
	row := q.db.QueryRow(ctx, insertDraftVersion,
		arg.DraftID,
		arg.Version,
		arg.Subject,
		arg.Body,
		arg.BodySha256,
		arg.ExtraContext,
		arg.CreatedBy,
	)
	var i DraftVersion
	err := row.Scan(
		&i.DraftID,
		&i.Version,
		&i.Subject,
		&i.Body,
		&i.BodySha256,
		&i.ExtraContext,
		&i.PromptContext,
		&i.Model,
		&i.ReservationID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDraftVersions = `-- name: ListDraftVersions :many
SELECT draft_id, version, subject, body, body_sha256, extra_context, prompt_context, model, reservation_id, created_by, created_at FROM draft_versions WHERE draft_id = $1 ORDER BY version DESC
`

func (q *Queries) ListDraftVersions(ctx context.Context, draftID uuid.UUID) ([]DraftVersion, error) {
	rows, err := q.db.Query(ctx, listDraftVersions, draftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DraftVersion{}
	for rows.Next() {
		var i DraftVersion
		if err := rows.Scan(
			&i.DraftID,
			&i.Version,
			&i.Subject,
			&i.Body,
			&i.BodySha256,
			&i.ExtraContext,
			&i.PromptContext,
			&i.Model,
			&i.ReservationID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
