// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertVoiceSample = `-- name: InsertVoiceSample :one
INSERT INTO voice_samples (id, owner_id, channel, text)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, channel, text, created_at
`

type InsertVoiceSampleParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Channel string
	Text    string
}

type InsertVoiceSampleRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Channel   string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) InsertVoiceSample(ctx context.Context, arg InsertVoiceSampleParams) (InsertVoiceSampleRow, error) {
	row := q.db.QueryRow(ctx, insertVoiceSample,
		arg.ID,
		arg.OwnerID,
		arg.Channel,
		arg.Text,
	)
	var i InsertVoiceSampleRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Channel,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
