// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getVoiceSampleText = `-- name: GetVoiceSampleText :one
SELECT text FROM voice_samples WHERE id = $1
`

func (q *Queries) GetVoiceSampleText(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVoiceSampleText, id)
	var text string
	err := row.Scan(&text)
	return text, err
}

const insertVoiceSample = `-- name: InsertVoiceSample :one
INSERT INTO voice_samples (id, owner_id, channel, text)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, channel, text, created_at
`

type InsertVoiceSampleParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Channel string
	Text    string
}

type InsertVoiceSampleRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Channel   string
	Text      string
	CreatedAt time.Time
}

func (q *Queries) InsertVoiceSample(ctx context.Context, arg InsertVoiceSampleParams) (InsertVoiceSampleRow, error) {
	row := q.db.QueryRow(ctx, insertVoiceSample,
		arg.ID,
		arg.OwnerID,
		arg.Channel,
		arg.Text,
	)
	var i InsertVoiceSampleRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Channel,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentVoiceSamples = `-- name: ListRecentVoiceSamples :many
SELECT id, owner_id, channel, text, created_at FROM voice_samples
WHERE owner_id = $1 AND channel = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListRecentVoiceSamplesParams struct {
	OwnerID  uuid.UUID
	Channel  string
	RowLimit int32
}

type ListRecentVoiceSamplesRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Channel   string
	Text      string
	CreatedAt time.Time
}

// The owner's newest samples for a channel, used when no embedding is there to
// rank them by similarity.
func (q *Queries) ListRecentVoiceSamples(ctx context.Context, arg ListRecentVoiceSamplesParams) ([]ListRecentVoiceSamplesRow, error) {
	rows, err := q.db.Query(ctx, listRecentVoiceSamples, arg.OwnerID, arg.Channel, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentVoiceSamplesRow{}
	for rows.Next() {
		var i ListRecentVoiceSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Channel,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimilarVoiceSamples = `-- name: ListSimilarVoiceSamples :many
SELECT id, owner_id, channel, text, created_at FROM voice_samples
WHERE owner_id = $1 AND channel = $2
ORDER BY embedding <=> $3::vector NULLS LAST, created_at DESC, id DESC
LIMIT $4
`

type ListSimilarVoiceSamplesParams struct {
	OwnerID  uuid.UUID
	Channel  string
	Query    *string
	RowLimit int32
}

type ListSimilarVoiceSamplesRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Channel   string
	Text      string
	CreatedAt time.Time
}

// The owner's samples for a channel closest to a query embedding. Samples with
// no embedding yet come last, newest first, so a fresh sample still counts.
func (q *Queries) ListSimilarVoiceSamples(ctx context.Context, arg ListSimilarVoiceSamplesParams) ([]ListSimilarVoiceSamplesRow, error) {
	rows, err := q.db.Query(ctx, listSimilarVoiceSamples,
		arg.OwnerID,
		arg.Channel,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSimilarVoiceSamplesRow{}
	for rows.Next() {
		var i ListSimilarVoiceSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Channel,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVoiceSampleEmbedding = `-- name: SetVoiceSampleEmbedding :execrows
UPDATE voice_samples SET embedding = $1::vector WHERE id = $2
`

type SetVoiceSampleEmbeddingParams struct {
	Embedding *string
	ID        uuid.UUID
}

func (q *Queries) SetVoiceSampleEmbedding(ctx context.Context, arg SetVoiceSampleEmbeddingParams) (int64, error) {
	result, err := q.db.Exec(ctx, setVoiceSampleEmbedding, arg.Embedding, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
