apiVersion: v1
kind: Service
metadata:
  name: shogun-postgres
  labels:
    app.kubernetes.io/name: shogun-postgres
    app.kubernetes.io/part-of: shogun
spec:
  selector:
    app.kubernetes.io/name: shogun-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
