#!/usr/bin/env python3
"""Maintain the per-service Helm charts and values.

Usage:
  scripts/helm.py add NAME   new service: values files, peers entry and chart
  scripts/helm.py sync       regenerate every service chart from deploy/helm/service
  scripts/helm.py check      exit 1 if a generated chart file is out of date

deploy/helm/service is a library chart: its templates and its values.yaml are the
single source. Each service gets deploy/helm/NAME with its own Chart.yaml (which
depends on the library), a copy of the defaults with name set, and a template that
includes the library's. Only Chart.yaml is hand-editable; sync never overwrites it.

Idempotent: existing values files are left alone.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HELM_DIR = ROOT / "deploy/helm"
CHART_VALUES = HELM_DIR / "service/values.yaml"
VALUES_DIR = HELM_DIR / "values"

PEERS_BEGIN = "  # peers begin\n"
PEERS_END = "  # peers end\n"
NAME_LINE = re.compile(r'^name: ""$', re.MULTILINE)
SERVICE_NAME = re.compile(r"[a-z][a-z0-9]*")

STAGING = """# {name}, staging. image.tag is bumped by .github/workflows/deploy.yml.
name: {name}
image:
  tag: "0.0.0"
env:
  ENVIRONMENT: staging
"""

PRODUCTION = """# {name}, production. image.tag is bumped by .github/workflows/deploy.yml.
name: {name}
image:
  tag: "0.0.0"
env:
  ENVIRONMENT: production
autoscaling:
  enabled: true
podDisruptionBudget:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi
"""

CHART = """apiVersion: v2
name: shogun-{name}
description: The {name} service.
type: application
version: 0.1.0
appVersion: "0.0.0"
dependencies:
  - name: shogun-service
    version: 0.1.0
    repository: file://../service
"""

VALUES_HEADER = """# Generated by scripts/helm.py sync from deploy/helm/service/values.yaml.
# Do not edit: change the defaults there, then run the script.
"""

RESOURCES = """{{- /* Generated by scripts/helm.py sync. Do not edit. */ -}}
{{ include "shogun.deployment" . }}
---
{{ include "shogun.service" . }}
---
{{ include "shogun.hpa" . }}
---
{{ include "shogun.pdb" . }}
---
{{ include "shogun.serviceMonitor" . }}
---
{{ include "shogun.migrationJob" . }}
"""


def fail(message: str) -> None:
    sys.exit(f"helm.py: {message}")


def check_name(name: str) -> None:
    if not SERVICE_NAME.fullmatch(name):
        fail(f"invalid service name {name!r}")


def read_defaults() -> str:
    text = CHART_VALUES.read_text()
    if PEERS_BEGIN not in text or PEERS_END not in text:
        fail(f"peers markers missing from {CHART_VALUES}")
    if not NAME_LINE.search(text):
        fail(f'`name: ""` missing from {CHART_VALUES}')
    return text


def peers_of(defaults: str) -> list[str]:
    block = defaults.split(PEERS_BEGIN, 1)[1].split(PEERS_END, 1)[0]
    return [line.strip()[2:] for line in block.splitlines() if line.strip().startswith("- ")]


def add_peer(defaults: str, name: str) -> str:
    entry = f"  - {name}\n"
    if entry in defaults:
        return defaults
    return defaults.replace(PEERS_END, entry + PEERS_END, 1)


def chart_values(defaults: str, name: str) -> str:
    return VALUES_HEADER + NAME_LINE.sub(f"name: {name}", defaults, count=1)


def generated_files(defaults: str, name: str) -> dict[pathlib.Path, str]:
    chart_dir = HELM_DIR / name
    return {
        chart_dir / "values.yaml": chart_values(defaults, name),
        chart_dir / "templates/resources.yaml": RESOURCES,
    }


def sync(defaults: str) -> None:
    for name in peers_of(defaults):
        chart_file = HELM_DIR / name / "Chart.yaml"
        files = generated_files(defaults, name)
        if not chart_file.exists():
            files = {**files, chart_file: CHART.format(name=name)}
        for path, text in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_text() != text:
                path.write_text(text)


def check(defaults: str) -> None:
    stale = []
    for name in peers_of(defaults):
        if not (HELM_DIR / name / "Chart.yaml").exists():
            stale.append(HELM_DIR / name / "Chart.yaml")
        for path, text in generated_files(defaults, name).items():
            if not path.exists() or path.read_text() != text:
                stale.append(path)
    if stale:
        listing = "\n".join(f"  {path.relative_to(ROOT)}" for path in stale)
        fail(f"out of date, run scripts/helm.py sync:\n{listing}")


def add(name: str) -> None:
    check_name(name)
    for env, template in (("staging", STAGING), ("production", PRODUCTION)):
        path = VALUES_DIR / env / f"{name}.yaml"
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text(template.format(name=name))

    defaults = add_peer(read_defaults(), name)
    CHART_VALUES.write_text(defaults)
    sync(defaults)
    print(f"helm.py: added {name}")


def main() -> None:
    args = sys.argv[1:]
    if len(args) == 2 and args[0] == "add":
        add(args[1])
    elif args == ["sync"]:
        sync(read_defaults())
    elif args == ["check"]:
        check(read_defaults())
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
