// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facts.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFacts = `-- name: CountFacts :one
SELECT count(*) FROM facts WHERE owner_id = $1 AND type = $2
`

type CountFactsParams struct {
	OwnerID uuid.UUID
	Type    string
}

func (q *Queries) CountFacts(ctx context.Context, arg CountFactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFacts, arg.OwnerID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertFact = `-- name: InsertFact :execrows
INSERT INTO facts (event_id, owner_id, type, dimension, occurred_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (event_id) DO NOTHING
`

type InsertFactParams struct {
	EventID    uuid.UUID
	OwnerID    uuid.UUID
	Type       string
	Dimension  []byte
	OccurredAt time.Time
}

// One fact per event id: a redelivered event stores nothing.
func (q *Queries) InsertFact(ctx context.Context, arg InsertFactParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFact,
		arg.EventID,
		arg.OwnerID,
		arg.Type,
		arg.Dimension,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
