// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type DailyRollup struct {
	OwnerID   uuid.UUID
	Day       time.Time
	Metric    string
	Dimension string
	Value     int64
}

type Fact struct {
	EventID    uuid.UUID
	OwnerID    uuid.UUID
	Type       string
	Dimension  []byte
	OccurredAt time.Time
}

type Inbox struct {
	EventID    uuid.UUID
	ReceivedAt time.Time
}

type Outbox struct {
	ID          uuid.UUID
	Type        string
	Source      string
	Subject     string
	Payload     []byte
	Traceparent string
	CreatedAt   time.Time
	DeliveredAt *time.Time
}
