// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rollups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRollupsFrom = `-- name: DeleteRollupsFrom :exec
DELETE FROM daily_rollups WHERE day >= $1
`

func (q *Queries) DeleteRollupsFrom(ctx context.Context, fromDay time.Time) error {
	_, err := q.db.Exec(ctx, deleteRollupsFrom, fromDay)
	return err
}

const listRollups = `-- name: ListRollups :many
SELECT day, metric, dimension, value FROM daily_rollups
WHERE owner_id = $1 AND day BETWEEN $2 AND $3 AND metric = ANY($4::text[])
ORDER BY day, metric, dimension
`

type ListRollupsParams struct {
	OwnerID uuid.UUID
	FromDay time.Time
	ToDay   time.Time
	Metrics []string
}

type ListRollupsRow struct {
	Day       time.Time
	Metric    string
	Dimension string
	Value     int64
}

func (q *Queries) ListRollups(ctx context.Context, arg ListRollupsParams) ([]ListRollupsRow, error) {
	rows, err := q.db.Query(ctx, listRollups,
		arg.OwnerID,
		arg.FromDay,
		arg.ToDay,
		arg.Metrics,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRollupsRow{}
	for rows.Next() {
		var i ListRollupsRow
		if err := rows.Scan(
			&i.Day,
			&i.Metric,
			&i.Dimension,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollupContactMoves = `-- name: RollupContactMoves :exec
INSERT INTO daily_rollups (owner_id, day, metric, dimension, value)
SELECT owner_id, (occurred_at AT TIME ZONE 'Asia/Kolkata')::date, 'contact_moves',
       'status=' || COALESCE(dimension->>'to', 'unknown'), count(*)
FROM facts
WHERE type = 'contact.status_changed' AND (occurred_at AT TIME ZONE 'Asia/Kolkata')::date >= $1
GROUP BY 1, 2, 3, 4
`

func (q *Queries) RollupContactMoves(ctx context.Context, fromDay time.Time) error {
	_, err := q.db.Exec(ctx, rollupContactMoves, fromDay)
	return err
}

const rollupContacts = `-- name: RollupContacts :exec
INSERT INTO daily_rollups (owner_id, day, metric, dimension, value)
SELECT owner_id, (occurred_at AT TIME ZONE 'Asia/Kolkata')::date,
       CASE dimension->>'to' WHEN 'reached_out' THEN 'outreach_sent' ELSE 'replies' END,
       'channel=' || COALESCE(dimension->>'channel', 'unknown'), count(*)
FROM facts
WHERE type = 'contact.status_changed' AND dimension->>'to' IN ('reached_out', 'replied')
  AND (occurred_at AT TIME ZONE 'Asia/Kolkata')::date >= $1
GROUP BY 1, 2, 3, 4
`

// First contacts and replies per day and channel, and moves per day and status.
func (q *Queries) RollupContacts(ctx context.Context, fromDay time.Time) error {
	_, err := q.db.Exec(ctx, rollupContacts, fromDay)
	return err
}

const rollupJobStages = `-- name: RollupJobStages :exec
INSERT INTO daily_rollups (owner_id, day, metric, dimension, value)
SELECT f.owner_id, (f.occurred_at AT TIME ZONE 'Asia/Kolkata')::date,
       CASE f.dimension->>'to'
         WHEN 'applied' THEN 'applications' WHEN 'shortlisted' THEN 'shortlisted'
         WHEN 'interview' THEN 'interviews' WHEN 'offer' THEN 'offers' ELSE 'rejections' END,
       'source=' || COALESCE(a.source, 'unknown'), count(*)
FROM facts f
LEFT JOIN LATERAL (
    SELECT added.dimension->>'source' AS source FROM facts added
    WHERE added.type = 'job.added' AND added.owner_id = f.owner_id
      AND added.dimension->>'job_id' = f.dimension->>'job_id'
    ORDER BY added.occurred_at LIMIT 1
) a ON true
WHERE f.type = 'job.status_changed'
  AND f.dimension->>'to' IN ('applied', 'shortlisted', 'interview', 'offer', 'rejected')
  AND (f.occurred_at AT TIME ZONE 'Asia/Kolkata')::date >= $1
GROUP BY 1, 2, 3, 4
`

// Moves into each stage per day, by the source the job was added from; a job
// sensei never saw added counts under source=unknown.
func (q *Queries) RollupJobStages(ctx context.Context, fromDay time.Time) error {
	_, err := q.db.Exec(ctx, rollupJobStages, fromDay)
	return err
}

const rollupJobsAdded = `-- name: RollupJobsAdded :exec
INSERT INTO daily_rollups (owner_id, day, metric, dimension, value)
SELECT owner_id, (occurred_at AT TIME ZONE 'Asia/Kolkata')::date, 'jobs_added',
       'source=' || COALESCE(dimension->>'source', 'unknown'), count(*)
FROM facts
WHERE type = 'job.added' AND (occurred_at AT TIME ZONE 'Asia/Kolkata')::date >= $1
GROUP BY 1, 2, 3, 4
`

// Jobs added per day and source.
func (q *Queries) RollupJobsAdded(ctx context.Context, fromDay time.Time) error {
	_, err := q.db.Exec(ctx, rollupJobsAdded, fromDay)
	return err
}
